INSERT INTO CUSTOMER (ID, NAME, SURNAME, CREDIT_LIMIT, USED_CREDIT_LIMIT) VALUES (1, 'ADMIN', 'ADMIN', 1000000, 0);
INSERT INTO CUSTOMER (ID, NAME, SURNAME, CREDIT_LIMIT, USED_CREDIT_LIMIT) VALUES (2, 'Esat', 'Akacık', 100000, 0);
INSERT INTO CUSTOMER (ID, NAME, SURNAME, CREDIT_LIMIT, USED_CREDIT_LIMIT) VALUES (3, 'User', 'User', 1000, 0);